### PR TITLE
Update MBition CLA and imprint

### PR DESCRIPTION
**Pull request by gunnar-mb**
Proposed changes:

- Making two copies of contributions file so that each one points to the right FOSS Co.
- Add MBition CLA PDF
- Correcting management names and emails in PROVIDER_INFORMATION / IMPRINT.

### CODE REVIEW

**Comment by cwege** [comment]
@gunnar-mb I can review and approve. But I have some doubts about the impact or renaming the CLA. 
@AnishaM7 @GATHYAM what happens with the CLA bot if we change the name of the CLA? And can we inform all users of the current file about the change?
@gunnar-mb maybe we need to introduce at mbition-specific file first and leave the existing intact for now.

**Comment by gunnar-mb** [comment]
OK, let's check first.  Thanks for reviewing.  
(We would love to use CLA bot also, by the way, so maybe we can sync up on how we may achieve that, with the MBition CLA also @AnishaM7 @GATHYAM ?)

**Comment by schr3gl3j** [comment]
@gunnar-mb As far as I remember, the data stored in the CLA Bot needs to be strongly separated due to the FOSS company's approach with the separation of legal entities (Mercedes-Benz Tech Innovation and MBition)
@cwege @GATHYAM @AnishaM7 If I remember correctly, the CLA Bot retrieves the CLA from a GitHub gist. However, I am not sure how this is actually handled. We have been discussing this for over a year.

**Comment by gunnar-mb** [comment]
New proposal for CLA update coming.
Will split IMPRINT update to separate PR instead.

**Comment by cwege** [comment]
Please just update the provider file. legal imprint is just here for historical reasons. It refers to provider info file.

**Pull request closed without merging**
